repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
      - id: cargo-check
      - id: clippy

  - repo: local
    hooks:
      - id: cargo-test
        name: Cargo Test
        pass_filenames: false
        types: [rust]
        language: system
        entry: cargo test --lib

      - id: cargo-doc
        name: Cargo Doc
        pass_filenames: false
        types: [rust]
        language: system
        entry: cargo doc
